---
title: "Proposed Sampling Locations 2026"
author: "John Phelan"
date: "2026-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(sf)
library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(dplyr)
library(bcdata)
library(readxl)
# Get onedrive path
# dat = sf::read_sf("app/www/sampling_results.gpkg")
# col = sf::read_sf("app/www/columbia_watershed.gpkg")
# subw = sf::read_sf("app/www/subwatershed_groups.gpkg"
dashboard_path <- here::here(
  "..",
  "AIS_WhirlingDiseaseDashboard",
  "app",
  "www"
)

dat <- sf::read_sf(file.path(dashboard_path, "sampling_results.gpkg"))
col <- sf::read_sf(file.path(dashboard_path, "columbia_watershed.gpkg"))
subw <- sf::read_sf(file.path(dashboard_path, "subwatershed_groups.gpkg"))
dat_2025 <- sf::read_sf(file.path(dashboard_path, "sampling_results_2025.gpkg"))
# get the watershed with Emerald Lake in it
# emerald_ws = sf::read_sf("app/www/emerald_lake_loc.gpkg") |> sf::st_transform(4326)

# Remove sites that weren't sampled.
dat = dat |> dplyr::filter(stringr::str_detect(sampled_in_2024_y_n, "^Y"))

# Convert levels for eDNA to 'Positive' and 'Negative'
# unique(dat$e_dna_results_mc)
# unique(dat$e_dna_results_tubifex)
# unique(dat$fish_sampling_results_q_pcr_mc_detected)
dat = dat |> 
  dplyr::mutate(e_dna_results_mc = dplyr::case_when(
    e_dna_results_mc == "Not Detected" ~ "Negative",
    !is.na(e_dna_results_mc) ~ "Positive",
    T ~ NA
  )) |> 
  dplyr::mutate(e_dna_results_tubifex = dplyr::case_when(
    e_dna_results_tubifex == "Not Detected" ~ "Negative",
    !is.na(e_dna_results_tubifex) ~ "Positive",
    T ~ NA
  ))

# unique(dat$e_dna_results_mc)
# unique(dat$e_dna_results_tubifex)
# unique(dat$fish_sampling_results_q_pcr_mc_detected)

# # Drop rows where sample result is NA for eDNA and fish
# dat = dat |> dplyr::filter(!(is.na(e_dna_results_mc) & is.na(e_dna_results_tubifex) & is.na(fish_sampling_results_q_pcr_mc_detected)))
# Replace true NA with 'NA' for rows with NO results but that claim to have been sampled. 
dat_no_results = dat |> 
  dplyr::filter((is.na(e_dna_results_mc) & is.na(e_dna_results_tubifex) & is.na(fish_sampling_results_q_pcr_mc_detected))) |> 
  dplyr::mutate(e_dna_results_mc = "NA",
                e_dna_results_tubifex = "NA",
                fish_sampling_results_q_pcr_mc_detected = "NA")

dat = dat |> 
  dplyr::filter(!(is.na(e_dna_results_mc) & is.na(e_dna_results_tubifex) & is.na(fish_sampling_results_q_pcr_mc_detected))) #|> 
# dplyr::bind_rows(dat_no_results)

rm(dat_no_results)

# Temporary correction to highlight NAs in dataset:
dat = dat |> dplyr::mutate(sampling_method = tidyr::replace_na(sampling_method, "NA"))

# Relabel the geometry column.
dat = sf::st_set_geometry(dat, "geom")

# Assign a colour based on sampling type, and also a colour based on test result.
dat = dat |> 
  dplyr::mutate(sample_type_colour = dplyr::case_when(
    sampling_method == "eDNA" ~ 'gold',
    sampling_method == "Fish" ~ 'salmon',
    # sampling_method == "Fish + eDNA" ~ 'gold',
    T ~ 'black'
  )) |> 
  dplyr::mutate(fish_results_colour = dplyr::case_when(
    fish_sampling_results_q_pcr_mc_detected == "Negative" ~ 'lightgreen',
    fish_sampling_results_q_pcr_mc_detected == "Positive" ~ 'purple',
    fish_sampling_results_q_pcr_mc_detected == "Pending" ~ 'pink',
    T ~ 'black'
  )) |> 
  dplyr::mutate(e_dna_myx_colour = ifelse(e_dna_results_mc == 'Positive', '#F97912', '#612073')) |> 
  dplyr::mutate(e_dna_tubifex_colour = ifelse(e_dna_results_tubifex == "Positive", "#F97912", "#612073"))

dat = dat |> 
  dplyr::mutate(e_dna_results_tubifex = ifelse(e_dna_results_tubifex == "Positive", "Present", "Absent"))

dat = dat |> 
  dplyr::mutate(
    delivery_agency = dplyr::case_when(
      delivery_agency == "ONA (Eleanor)" ~ "ONA",
      delivery_agency == "ONA (Sam)" ~ "ONA",
      delivery_agency == "WLRS - AEB fisheries" ~ "WLRS",
      delivery_agency == "WLRS (COS AIS inspectors)" ~ "WLRS",
      delivery_agency == "WLRS - region 3" ~ "WLRS",
      delivery_agency == "WLRS (headquarters)" ~ "WLRS",
      delivery_agency == "WLRS - Kootenay region" ~ "WLRS",
      delivery_agency == "WLRS Cultus" ~ "WLRS",
      delivery_agency == "WLRS Region 2" ~ "WLRS",
      TRUE ~ delivery_agency
    )
  )

dat <- dat |>
  dplyr::mutate(
    date_collected = lubridate::parse_date_time(
      date_collected,
      orders = c("Ymd", "mdY", "dmy", "Y/m/d", "m/d/Y", "d/m/Y", "Ymd HMS"),
      quiet = TRUE
    ) |>
      as.Date() |>
      as.character()
  )


#-----------------------------------------------------------------------------------------------------------


# 
# dat_2025 = dat_2025 |> dplyr::filter(stringr::str_detect(confirmed_to_have_been_sampled_in_2025_y_n, "^Y"))
# 


dat_2025 = dat_2025 |> 
  dplyr::rename(reach = sub_watershed_reach_name, sample_site_name = final_sample_site_name,
                delivery_agency = sampling_organization, sampled_in_2025_y_n = confirmed_to_have_been_sampled_in_2025_y_n,
                e_dna_results_mc = result_mc)

dat_2025$e_dna_results_tubifex = NA

# dat_2025 = dat_2025 |> 
#   dplyr::mutate(e_dna_results_mc = dplyr::case_when(
#     e_dna_results_mc == "Not Detected" ~ "Negative",
#     !is.na(e_dna_results_mc) ~ "Positive",
#     T ~ NA
#   )) |> 
#   dplyr::mutate(e_dna_results_tubifex = dplyr::case_when(
#     e_dna_results_tubifex == "Not Detected" ~ "Negative",
#     !is.na(e_dna_results_tubifex) ~ "Positive",
#     T ~ NA
#   ))

dat_no_results_2025 = dat_2025 |> 
  dplyr::filter((is.na(e_dna_results_mc) & is.na(e_dna_results_tubifex) & is.na(fish_sampling_results_q_pcr_mc_detected))) |> 
  dplyr::mutate(e_dna_results_mc = "NA",
                e_dna_results_tubifex = "NA",
                fish_sampling_results_q_pcr_mc_detected = "NA")

# dat_2025 = dat_2025 |>
#   dplyr::filter(!(is.na(e_dna_results_mc) & is.na(e_dna_results_tubifex) & is.na(fish_sampling_results_q_pcr_mc_detected))) #|>
# dplyr::bind_rows(dat_no_results)

## Placeholder as this is not in the results
dat_2025 = dat_2025 |> 
  dplyr::rename(fish_species_sampled = fish_species)


dat_2025 = dat_2025 |> 
  dplyr::mutate(sample_type_colour = dplyr::case_when(
    sampling_method == "eDNA" ~ 'gold',
    sampling_method == "Fish" ~ 'salmon',
    # sampling_method == "Fish + eDNA" ~ 'gold',
    T ~ 'black'
  )) |> 
  dplyr::mutate(fish_results_colour = dplyr::case_when(
    fish_sampling_results_q_pcr_mc_detected == "Negative" ~ 'lightgreen',
    fish_sampling_results_q_pcr_mc_detected == "Positive" ~ 'purple',
    fish_sampling_results_q_pcr_mc_detected == "Pending" ~ 'pink',
    T ~ 'black'
  )) |> 
  dplyr::mutate(e_dna_myx_colour = ifelse(e_dna_results_mc == 'Positive', '#F97912', '#612073')) |> 
  dplyr::mutate(e_dna_tubifex_colour = ifelse(e_dna_results_tubifex == "Positive", "#F97912", "#612073"))

dat_2025 = dat_2025 |> 
  dplyr::mutate(e_dna_results_tubifex = ifelse(e_dna_results_tubifex == "Positive", "Present", "Absent"))

dat_2025 = dat_2025 |> 
  dplyr::mutate(
    delivery_agency = dplyr::case_when(
      delivery_agency == "ONA (Eleanor)" ~ "ONA",
      delivery_agency == "ONA (Sam)" ~ "ONA",
      delivery_agency == "WLRS - AEB fisheries" ~ "WLRS",
      delivery_agency == "WLRS (COS AIS inspectors)" ~ "WLRS",
      delivery_agency == "WLRS - region 3" ~ "WLRS",
      delivery_agency == "WLRS (headquarters)" ~ "WLRS",
      delivery_agency == "WLRS - Kootenay region" ~ "WLRS",
      delivery_agency == "WLRS Cultus" ~ "WLRS",
      delivery_agency == "WLRS Region 2" ~ "WLRS",
      TRUE ~ delivery_agency
    )
  )

dat_2025 <- dat_2025 |>
  dplyr::mutate(
    date_collected = lubridate::parse_date_time(
      date_collected,
      orders = c("Ymd", "mdY", "dmy", "Y/m/d", "m/d/Y", "d/m/Y", "Ymd HMS"),
      quiet = TRUE
    ) |>
      as.Date() |>
      as.character()
  ) |> 
  dplyr::mutate(e_dna_results_tubifex = NA)


#------------
# New request - no more tubifex

dat = dat |> 
  dplyr::select(-e_dna_results_tubifex) |> 
  dplyr::mutate(Year = 2024)

dat_2025 = dat_2025 |> 
  dplyr::select(-e_dna_results_tubifex) |> 
  dplyr::mutate(Year = 2025)


dat <- dat |>
  dplyr::mutate(
    date_collected = lubridate::parse_date_time(
      date_collected,
      orders = c("Ymd", "mdY", "dmy", "Y/m/d", "m/d/Y", "d/m/Y", "Ymd HMS"),
      quiet = TRUE
    ) |>
      as.Date() |>
      as.character()
  )


#---- combine the data ------#
dat_all = dplyr::bind_rows(dat,dat_2025) 

dat_all = dat_all |> 
  dplyr::select(-c(original_lat,original_long))

dat_all = dat_all |> 
  dplyr::mutate(
    delivery_agency = dplyr::case_when(
      delivery_agency == "ONA (Eleanor)" ~ "ONA",
      delivery_agency == "ONA (Sam)" ~ "ONA",
      delivery_agency == "WLRS - AEB fisheries" ~ "WLRS",
      delivery_agency == "WLRS (COS AIS inspectors)" ~ "WLRS",
      delivery_agency == "WLRS - region 3" ~ "WLRS",
      delivery_agency == "WLRS (headquarters)" ~ "WLRS",
      delivery_agency == "WLRS - Kootenay region" ~ "WLRS",
      delivery_agency == "WLRS Cultus" ~ "WLRS",
      delivery_agency == "WLRS Region 2" ~ "WLRS",
      TRUE ~ delivery_agency
    )
  )






```

```{r get_porposed_locations}

proposed_locations<-read_xlsx(here::here("./data/proposedlocation2026.xlsx"))


proposed_locations_sf <- proposed_locations %>%
  filter(
    !is.na(Longitude),
    !is.na(Latitude)
  ) %>%
  st_as_sf(
    coords = c("Longitude", "Latitude"),
    crs = 4326,
    remove = FALSE
  )

```

```{r proposed_map, fig.width=10, fig.height=8}

pal <- c(
  "2024" = "#1b9e77",
  "2025" = "#d95f02",
  "Proposed 2026" = "#7570b3"
)

proposed_locations_sf <- proposed_locations_sf |>
  janitor::clean_names()

library(dplyr)
library(stringr)

proposed_locations_sf <- proposed_locations_sf |>
  mutate(
    anticipated_sampling_date = case_when(
      str_detect(anticipated_sampling_date, "^\\d+$") ~
        as.character(
          as.Date(as.numeric(anticipated_sampling_date),
                  origin = "1899-12-30")
        ),
      
      anticipated_sampling_date == "Sep 03 - 18" ~
        "2026-09-03",  # choose start date
      
      TRUE ~ anticipated_sampling_date
    ),
    anticipated_sampling_date = as.Date(anticipated_sampling_date)
  )

leaflet() |>
  addProviderTiles(providers$CartoDB, group = "CartoDB") |>

  # Watershed (optional)
  addPolygons(
    data = col,
    color = "black",
    weight = 2,
    fill = FALSE,
    group = "Columbia Watershed"
  ) |>

  # 2024
  addCircleMarkers(
  data = dplyr::filter(dat_all, Year == 2024),
  radius = 5,
  stroke = TRUE,
  color = "black",
  weight = 1,
  fill = TRUE,
  fillColor = ~I("#1b9e77"),
  fillOpacity = 1,
  group = "2024",
  popup = ~paste0(
  "<b>", sample_site_name, "</b><br>",
  "<b>Sample Type:</b> ", sampling_method, "<br>",
  "<b>Delivery Agency:</b> ", delivery_agency
)
)|>

  # 2025
  addCircleMarkers(
  data = dplyr::filter(dat_all, Year == 2025),
  radius = 5,
  stroke = TRUE,
  color = "black",
  weight = 1,
  fill = TRUE,
  fillColor = ~I("#d95f02"),
  fillOpacity = 1,
  group = "2025",
  popup = ~paste0(
  "<b>", sample_site_name, "</b><br>",
  "<b>Sample Type:</b> ", sampling_method, "<br>",
  "<b>Delivery Agency:</b> ", delivery_agency
)
)|>

  # Proposed
  addCircleMarkers(
  data = proposed_locations_sf,
  radius = 7,
  stroke = TRUE,
  color = "black",
  weight = 2,
  fill = TRUE,
  fillColor = ~I("#7570b3"),
  fillOpacity = 1,
  group = "Proposed 2026",
  popup = ~paste0(
  "<b> Waterbody Name: </b>", waterbody_name, "<br>",
  "<b>Sample Location Name: </b> ", sample_site_name_unique_and_descriptive, "<br>",
  "<b>Anticipated Sampling Date: </b> ", anticipated_sampling_date, "<br>"
)
)|>

  addLayersControl(
    overlayGroups = c(
      "2024",
      "2025",
      "Proposed 2026",
      "Columbia Watershed"
    ),
    options = layersControlOptions(collapsed = FALSE)
  ) |> 
addLegend(
  position = "bottomright",
  colors = c("#1b9e77", "#d95f02", "#7570b3"),
  labels = c("2024", "2025", "Proposed 2026"),
  title = "Sampling Year",
  opacity = 1
)

```


